FROM golang:1.16

WORKDIR /go/src
ENV PATH="/go/bin:${PATH}"

RUN apt-get update && \
    apt-get install build-essential librdkafka-dev -y

COPY . .
RUN GOOS=linux go build -ldflags="-s -w" -o simulator
ENTRYPOINT ["./simulator"]


## construindo e imagem e publicando no dockerhub
## docker build -t phelipperibeiro/app-delivery-simulator -f Dockerfile.prod .
## docker push phelipperibeiro/app-delivery-simulator